name: Manager and Agent connection test

on: [push, workflow_dispatch]

env:
  CHEF_LICENSE: accept-no-persist

jobs:
  manager-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          ubuntu-2004,
          ubuntu-2204,
          ubuntu-2404,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Setup Ruby
      uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
      with:
        ruby-version: '3.1'
    - name: Install dependencies
      run: |
        bundle config set --local without 'vagrant'
        bundle install

    - name: Install manager
      uses: actionshub/test-kitchen@86151766b9985d3765e26a9bf1c990d89015dc40 # main
      env:
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-manager
        os: ${{ matrix.os }}
        action: converge

    - name: Install agent
      uses: actionshub/test-kitchen@86151766b9985d3765e26a9bf1c990d89015dc40 # main
      env:
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-agent
        os: ${{ matrix.os }}
        action: converge

    - name: Test manager and agent connection
      uses: actionshub/test-kitchen@86151766b9985d3765e26a9bf1c990d89015dc40 # main
      env:
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-agent
        os: ${{ matrix.os }}
        action: verify
