name: Manager and Agent connection test

on: [push, workflow_dispatch]

jobs:
  manager-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          ubuntu-2004,
          ubuntu-2204,
          ubuntu-2404,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
    - name: Install dependencies
      run: |
        bundle config set --local without 'vagrant'
        bundle install

    - name: Install Chef
      uses: actionshub/chef-install@main

    - name: Install manager
      uses: actionshub/test-kitchen@main
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-manager
        os: ${{ matrix.os }}
        action: converge

    - name: Install agent
      uses: actionshub/test-kitchen@main
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-agent
        os: ${{ matrix.os }}
        action: converge

    - name: Test manager and agent connection
      uses: actionshub/test-kitchen@main
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      with:
        suite: wazuh-agent
        os: ${{ matrix.os }}
        action: verify
